services:

  product:
    build: 
      context: ./
      dockerfile: docker/Dockerfile
    image: gustavo0426/microservice-product-h2:${IMAGE_VERSION}
    container_name: microservice-product
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - product_network
    ports:
      - "80:${SERVER_PORT}"

networks:
  product_network:
    name: product_network
    driver: bridge