spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

api:
  version: v1

spring-doc:
  swagger-ui:
    path: /${api.version}/product/           # http://{host}:{port}/{api.version}/product/swagger-ui/index.html
  api-docs:
    path: /${api.version}/product/api-docs   # http://{host}:{port}/{api.version}/product/api-docs

logging:
  level:
    org.springframework.security: debug

server:
  port: ${SERVER_PORT}