spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

api:
  version: v1

# swagger = http://{host}:{port}/{api.version}/custom-swagger/swagger-ui/index.html
# swagger = http://{host}:{port}/{api.version}/custom-docs

spring-doc:
  api-docs:
    path: /${api.version}/custom-docs # Cambia la ruta del JSON de OpenAPI
  swagger-ui:
    path: /${api.version}/custom-swagger/ # Cambia la ruta de Swagger UI

logging:
  level:
    org.springframework.security: debug

server:
  port: ${SERVER_PORT}