services:

  product:
    build: 
      context: ../
      dockerfile: docker-compose/Dockerfile
    image: gustavo0426/test-product-microservice-h2:latest
    container_name: test-product-microservice
    restart: always
    environment:
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - test-product-network
    ports:
      - "9092:${SERVER_PORT}"

networks:
  test-product-network:
    name: test-product-network
    driver: bridge  