services:

  TEMPLATE_SERVICE_NAME:
    build: 
      context: ../
      dockerfile: docker-compose/Dockerfile
    image: gustavo0426/TEMPLATE_IMAGE_NAME:latest
    container_name: TEMPLATE_CONTAINER_NAME
    restart: always
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - TEMPLATE_SERVICE_NAME_network
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

networks:
  TEMPLATE_SERVICE_NAME_network:
    name: TEMPLATE_SERVICE_NAME_network
    driver: bridge  